# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Android Image Slider
description: >- # this means to ignore newlines until "baseurl:"
  An image slider for android that let you pick the image loader library that best suits your needs.
show_downloads: "true"

# Theme configurations
repository: ouattararomuald/ouattararomuald.github.io
github:
  is_project_page: "true"
  repository_name: "android-image-slider"
  zip_url: https://github.com/ouattararomuald/android-image-slider/archive/master.zip
  another_url: another value

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
